const data = [
  {
    targetId: "0miiii",
    taste: 7,
    values: 5,
    personality: 4,
    total: 16,
  },
  {
    targetId: "2Estella",
    taste: 4,
    values: 7,
    personality: 1,
    total: 12,
  },
  {
    targetId: "Amelia-Shin",
    taste: 4,
    values: 7,
    personality: 5,
    total: 16,
  },
  {
    targetId: "BBAK-jun",
    taste: 7,
    values: 7,
    personality: 2,
    total: 16,
  },
  {
    targetId: "BangDori",
    taste: 7,
    values: 7,
    personality: 4,
    total: 18,
  },
  {
    targetId: "DEV4N4",
    taste: 6,
    values: 4,
    personality: 4,
    total: 14,
  },
  {
    targetId: "Hwirin-Kim",
    taste: 7,
    values: 7,
    personality: 2,
    total: 16,
  },
  {
    targetId: "JHeeJinDev",
    taste: 4,
    values: 8,
    personality: 2,
    total: 14,
  },
  {
    targetId: "JiHoon-0330",
    taste: 3,
    values: 8,
    personality: 4,
    total: 15,
  },
  {
    targetId: "JungWoo0203",
    taste: 7,
    values: 5,
    personality: 6,
    total: 18,
  },
  {
    targetId: "JunilHwang",
    taste: 5,
    values: 7,
    personality: 3,
    total: 15,
  },
  {
    targetId: "Legitgoons",
    taste: 5,
    values: 7,
    personality: 3,
    total: 15,
  },
  {
    targetId: "Yangs1s",
    taste: 3,
    values: 6,
    personality: 4,
    total: 13,
  },
  {
    targetId: "YeongseoYoon-hanghae",
    taste: 7,
    values: 7,
    personality: 2,
    total: 16,
  },
  {
    targetId: "Yuyeol",
    taste: 7,
    values: 8,
    personality: 4,
    total: 19,
  },
  {
    targetId: "adds-bug",
    taste: 3,
    values: 7,
    personality: 2,
    total: 12,
  },
  {
    targetId: "adds9810",
    taste: 10,
    values: 8,
    personality: 4,
    total: 22,
  },
  {
    targetId: "angielxx",
    taste: 5,
    values: 3,
    personality: 4,
    total: 12,
  },
  {
    targetId: "areumH",
    taste: 7,
    values: 7,
    personality: 7,
    total: 21,
  },
  {
    targetId: "bebusl",
    taste: 6,
    values: 6,
    personality: 3,
    total: 15,
  },
  {
    targetId: "chan9yu",
    taste: 4,
    values: 5,
    personality: 2,
    total: 11,
  },
  {
    targetId: "chb6734",
    taste: 8,
    values: 6,
    personality: 0,
    total: 14,
  },
  {
    targetId: "creco-hanghae",
    taste: 6,
    values: 4,
    personality: 3,
    total: 13,
  },
  {
    targetId: "devchaeyoung",
    taste: 6,
    values: 5,
    personality: 5,
    total: 16,
  },
  {
    targetId: "devchangjun",
    taste: 4,
    values: 4,
    personality: 4,
    total: 12,
  },
  {
    targetId: "developer-1px",
    taste: 8,
    values: 9,
    personality: 2,
    total: 19,
  },
  {
    targetId: "esoby",
    taste: 6,
    values: 7,
    personality: 2,
    total: 15,
  },
  {
    targetId: "eveneul",
    taste: 7,
    values: 8,
    personality: 2,
    total: 17,
  },
  {
    targetId: "heojungseok",
    taste: 7,
    values: 7,
    personality: 4,
    total: 18,
  },
  {
    targetId: "hty0525",
    taste: 6,
    values: 8,
    personality: 1,
    total: 15,
  },
  {
    targetId: "hyemin-teamsparta",
    taste: 8,
    values: 8,
    personality: 3,
    total: 19,
  },
  {
    targetId: "hyunzsu",
    taste: 5,
    values: 7,
    personality: 3,
    total: 15,
  },
  {
    targetId: "j2h30728",
    taste: 6,
    values: 4,
    personality: 5,
    total: 15,
  },
  {
    targetId: "jeongmingi123",
    taste: 6,
    values: 9,
    personality: 4,
    total: 19,
  },
  {
    targetId: "jinsoul75",
    taste: 6,
    values: 7,
    personality: 3,
    total: 16,
  },
  {
    targetId: "jun17183",
    taste: 7,
    values: 6,
    personality: 6,
    total: 19,
  },
  {
    targetId: "jung-han",
    taste: 5,
    values: 4,
    personality: 3,
    total: 12,
  },
  {
    targetId: "k-sang-soo",
    taste: 4,
    values: 5,
    personality: 4,
    total: 13,
  },
  {
    targetId: "ldhldh07",
    taste: 6,
    values: 3,
    personality: 3,
    total: 12,
  },
  {
    targetId: "lieblichoi",
    taste: 5,
    values: 8,
    personality: 4,
    total: 17,
  },
  {
    targetId: "minjaeleee",
    taste: 6,
    values: 8,
    personality: 3,
    total: 17,
  },
  {
    targetId: "nemobim",
    taste: 6,
    values: 6,
    personality: 4,
    total: 16,
  },
  {
    targetId: "nimusmix",
    taste: 7,
    values: 5,
    personality: 5,
    total: 17,
  },
  {
    targetId: "pitangland",
    taste: 4,
    values: 6,
    personality: 2,
    total: 12,
  },
  {
    targetId: "q1Lim",
    taste: 6,
    values: 7,
    personality: 6,
    total: 19,
  },
  {
    targetId: "realstone2",
    taste: 6,
    values: 8,
    personality: 6,
    total: 20,
  },
  {
    targetId: "shiren",
    taste: 8,
    values: 6,
    personality: 5,
    total: 19,
  },
  {
    targetId: "soyalattee",
    taste: 7,
    values: 5,
    personality: 3,
    total: 15,
  },
  {
    targetId: "suhyeon57",
    taste: 5,
    values: 5,
    personality: 2,
    total: 12,
  },
  {
    targetId: "susmisc14",
    taste: 5,
    values: 7,
    personality: 4,
    total: 16,
  },
  {
    targetId: "taeyeong0814",
    taste: 6,
    values: 6,
    personality: 5,
    total: 17,
  },
  {
    targetId: "tomatopickles404",
    taste: 5,
    values: 7,
    personality: 3,
    total: 15,
  },
  {
    targetId: "tooth-is-silver",
    taste: 9,
    values: 6,
    personality: 5,
    total: 20,
  },
  {
    targetId: "unseoJang",
    taste: 6,
    values: 7,
    personality: 3,
    total: 16,
  },
  {
    targetId: "yangchanghun",
    taste: 4,
    values: 3,
    personality: 3,
    total: 10,
  },
  {
    targetId: "yhun940731",
    taste: 5,
    values: 9,
    personality: 4,
    total: 18,
  },
  {
    targetId: "yuhyeon99",
    taste: 6,
    values: 8,
    personality: 2,
    total: 16,
  },
  {
    targetId: "yunwoo-yu",
    taste: 7,
    values: 7,
    personality: 5,
    total: 19,
  },
  {
    targetId: "zenna9",
    taste: 8,
    values: 6,
    personality: 4,
    total: 18,
  },
];

// 가중치 적용하여 최종 점수 계산 및 순위 정렬
const rankedData = data
  .map((item) => ({
    ...item,
    finalScore: item.taste * 2 + item.values * 4 + item.personality * 4,
  }))
  .sort((a, b) => b.finalScore - a.finalScore)
  .map((item, index) => ({
    ...item,
    rank: index + 1,
  }));

console.log("최종 점수 순위:");
rankedData.forEach((item) => {
  console.log(`${item.rank}위: ${item.targetId} - 최종점수: ${item.finalScore}`);
});
